package Exception;

public class Throw {
    public static void main(String[] args) {
        try {
            validateNumber(-5); // This will throw an exception
        } catch (IllegalArgumentException e) {
            System.out.println("Caught exception: " + e.getMessage());
        }
    }

    public static void validateNumber(int number) {
        if (number < 0) {
            // Manually creating and throwing an exception
            throw new IllegalArgumentException("Number must be non-negative.");
        }
        // this can be done to handle in same method
        // try {
        // if (number < 0) {
        // Manually creating and throwing an exception
        // throw new IllegalArgumentException("Number must be non-negative.");
        // }
        // } catch (Exception e) {
        // System.out.println(e);
        // }
        System.out.println("Number is valid.");
    }

    // The throw keyword is used to throw an error, which can either be generated by
    // the JVM or manually created by the developer. This error can be propagated to
    // the calling method, or it can be handled within the same method using a
    // try-catch block
}
